In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('toy.csv')

In [3]:
dataset

Number    City  Gender  Age    Income Illness
0            1  Dallas    Male   41   40367.0      No
1            2  Dallas    Male   54   45084.0      No
2            3  Dallas    Male   42   52483.0      No
3            4  Dallas    Male   40   40941.0      No
4            5  Dallas    Male   46   50289.0      No
...        ...     ...     ...  ...       ...     ...
149995  149996  Austin    Male   48   93669.0      No
149996  149997  Austin    Male   25   96748.0      No
149997  149998  Austin    Male   26  111885.0      No
149998  149999  Austin    Male   25  111878.0      No
149999  150000  Austin  Female   37   87251.0      No

[150000 rows x 6 columns]

In [6]:
x = dataset[['City', 'Gender', 'Age', 'Income']].values

In [7]:
x

array([['Dallas', 'Male', 41, 40367.0],
       ['Dallas', 'Male', 54, 45084.0],
       ['Dallas', 'Male', 42, 52483.0],
       ...,
       ['Austin', 'Male', 26, 111885.0],
       ['Austin', 'Male', 25, 111878.0],
       ['Austin', 'Female', 37, 87251.0]], dtype=object)

In [10]:
y = dataset[['Illness']].values

In [11]:
y

array([['No'],
       ['No'],
       ['No'],
       ...,
       ['No'],
       ['No'],
       ['No']], dtype=object)

In [12]:
from sklearn.impute import SimpleImputer

In [14]:
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

In [15]:
imputer = imputer.fit(x[:,2:4])

In [16]:
x[:,2:4] = imputer.transform(x[:,2:4])

In [17]:
x

array([['Dallas', 'Male', 41.0, 40367.0],
       ['Dallas', 'Male', 54.0, 45084.0],
       ['Dallas', 'Male', 42.0, 52483.0],
       ...,
       ['Austin', 'Male', 26.0, 111885.0],
       ['Austin', 'Male', 25.0, 111878.0],
       ['Austin', 'Female', 37.0, 87251.0]], dtype=object)

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
label_encoder_x = LabelEncoder()

In [21]:
x[:,1] = label_encoder_x.fit_transform(x[:,1])

In [22]:
x

array([['Dallas', 1, 41.0, 40367.0],
       ['Dallas', 1, 54.0, 45084.0],
       ['Dallas', 1, 42.0, 52483.0],
       ...,
       ['Austin', 1, 26.0, 111885.0],
       ['Austin', 1, 25.0, 111878.0],
       ['Austin', 0, 37.0, 87251.0]], dtype=object)

In [23]:
x[:,0] = label_encoder_x.fit_transform(x[:,0])

In [24]:
x

array([[2, 1, 41.0, 40367.0],
       [2, 1, 54.0, 45084.0],
       [2, 1, 42.0, 52483.0],
       ...,
       [0, 1, 26.0, 111885.0],
       [0, 1, 25.0, 111878.0],
       [0, 0, 37.0, 87251.0]], dtype=object)

In [25]:
from sklearn.preprocessing import OneHotEncoder

In [26]:
one_hot_encoder = OneHotEncoder()

In [36]:
x_city = one_hot_encoder.fit_transform(dataset.City.values.reshape(-1,1)).toarray()

In [37]:
x_city

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.]])

In [38]:
label_encoder_y = LabelEncoder()

In [39]:
y = label_encoder_y.fit_transform(y)

In [40]:
y

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [41]:
from sklearn.model_selection import train_test_split

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [43]:
x_train

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [44]:
x_test

array([[0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])