In [31]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [32]:
dataset = pd.read_csv('Crop_recommendation.csv')

In [33]:
dataset

Nitrogen_Soil  Phosphorus_Soil  potassium_Soil  temperature   humidity  \
0                90               42              43    20.879744  82.002744   
1                85               58              41    21.770462  80.319644   
2                60               55              44    23.004459  82.320763   
3                74               35              40    26.491096  80.158363   
4                78               42              42    20.130175  81.604873   
...             ...              ...             ...          ...        ...   
2195            107               34              32    26.774637  66.413269   
2196             99               15              27    27.417112  56.636362   
2197            118               33              30    24.131797  67.225123   
2198            117               32              34    26.272418  52.127394   
2199            104               18              30    23.603016  60.396475   

            ph    rainfall   label  
0     6.502985  202.935536    rice  
1     7.038096  226.655537    rice  
2     7.840207  263.964248    rice  
3     6.980401  242.864034    rice  
4     7.628473  262.717340    rice  
...        ...         ...     ...  
2195  6.780064  177.774507  coffee  
2196  6.086922  127.924610  coffee  
2197  6.362608  173.322839  coffee  
2198  6.758793  127.175293  coffee  
2199  6.779833  140.937041  coffee  

[2200 rows x 8 columns]

In [34]:
df = dataset.values

In [35]:
df

array([[90, 42, 43, ..., 6.502985292, 202.9355362, 'rice'],
       [85, 58, 41, ..., 7.038096361, 226.6555374, 'rice'],
       [60, 55, 44, ..., 7.840207144, 263.9642476, 'rice'],
       ...,
       [118, 33, 30, ..., 6.362607851, 173.3228386, 'coffee'],
       [117, 32, 34, ..., 6.758792552, 127.1752928, 'coffee'],
       [104, 18, 30, ..., 6.779832611, 140.9370415, 'coffee']],
      dtype=object)

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
label_encoder_df = LabelEncoder()

In [38]:
df[:,7] = label_encoder_df.fit_transform(df[:,7])

In [39]:
df

array([[90, 42, 43, ..., 6.502985292, 202.9355362, 20],
       [85, 58, 41, ..., 7.038096361, 226.6555374, 20],
       [60, 55, 44, ..., 7.840207144, 263.9642476, 20],
       ...,
       [118, 33, 30, ..., 6.362607851, 173.3228386, 5],
       [117, 32, 34, ..., 6.758792552, 127.1752928, 5],
       [104, 18, 30, ..., 6.779832611, 140.9370415, 5]], dtype=object)

In [40]:
dataset.label = df[:,7]

In [41]:
dataset

Nitrogen_Soil  Phosphorus_Soil  potassium_Soil  temperature   humidity  \
0                90               42              43    20.879744  82.002744   
1                85               58              41    21.770462  80.319644   
2                60               55              44    23.004459  82.320763   
3                74               35              40    26.491096  80.158363   
4                78               42              42    20.130175  81.604873   
...             ...              ...             ...          ...        ...   
2195            107               34              32    26.774637  66.413269   
2196             99               15              27    27.417112  56.636362   
2197            118               33              30    24.131797  67.225123   
2198            117               32              34    26.272418  52.127394   
2199            104               18              30    23.603016  60.396475   

            ph    rainfall label  
0     6.502985  202.935536    20  
1     7.038096  226.655537    20  
2     7.840207  263.964248    20  
3     6.980401  242.864034    20  
4     7.628473  262.717340    20  
...        ...         ...   ...  
2195  6.780064  177.774507     5  
2196  6.086922  127.924610     5  
2197  6.362608  173.322839     5  
2198  6.758793  127.175293     5  
2199  6.779833  140.937041     5  

[2200 rows x 8 columns]

In [42]:
reg = linear_model.LinearRegression()

In [43]:
reg.fit(dataset[['Nitrogen_Soil', 'Phosphorus_Soil', 'potassium_Soil', 'temperature', 'humidity', 'ph', 'rainfall']], dataset['label'])

LinearRegression()

In [44]:
reg.coef_

array([-3.05291991e-02, -8.88100369e-02, -9.75943570e-03,  9.30850410e-03,
        5.30009114e-02, -5.78634783e-01, -2.97133790e-04])

In [45]:
reg.intercept_

16.999520640148294

In [46]:
reg.predict([[74, 35, 40, 26.491096, 80.158363, 6.980401, 242.864034]])

F:\4-2\conda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.62542403])

In [47]:
reg.predict([[74, 35, 40, 26.491096, 80.158363, 6.980401, 242.864034]])

F:\4-2\conda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.62542403])

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [49]:
x = dataset[['Nitrogen_Soil', 'Phosphorus_Soil', 'potassium_Soil', 'temperature', 'humidity', 'ph', 'rainfall']]
y = dataset[['label']]

In [50]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)

In [51]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [52]:
y_pred = model.predict(x_test)

In [53]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

In [54]:
rmse

5.236256998435687

In [55]:
df

array([[90, 42, 43, ..., 6.502985292, 202.9355362, 20],
       [85, 58, 41, ..., 7.038096361, 226.6555374, 20],
       [60, 55, 44, ..., 7.840207144, 263.9642476, 20],
       ...,
       [118, 33, 30, ..., 6.362607851, 173.3228386, 5],
       [117, 32, 34, ..., 6.758792552, 127.1752928, 5],
       [104, 18, 30, ..., 6.779832611, 140.9370415, 5]], dtype=object)

In [56]:
dataset

Nitrogen_Soil  Phosphorus_Soil  potassium_Soil  temperature   humidity  \
0                90               42              43    20.879744  82.002744   
1                85               58              41    21.770462  80.319644   
2                60               55              44    23.004459  82.320763   
3                74               35              40    26.491096  80.158363   
4                78               42              42    20.130175  81.604873   
...             ...              ...             ...          ...        ...   
2195            107               34              32    26.774637  66.413269   
2196             99               15              27    27.417112  56.636362   
2197            118               33              30    24.131797  67.225123   
2198            117               32              34    26.272418  52.127394   
2199            104               18              30    23.603016  60.396475   

            ph    rainfall label  
0     6.502985  202.935536    20  
1     7.038096  226.655537    20  
2     7.840207  263.964248    20  
3     6.980401  242.864034    20  
4     7.628473  262.717340    20  
...        ...         ...   ...  
2195  6.780064  177.774507     5  
2196  6.086922  127.924610     5  
2197  6.362608  173.322839     5  
2198  6.758793  127.175293     5  
2199  6.779833  140.937041     5  

[2200 rows x 8 columns]

In [68]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

In [69]:
model = KNeighborsRegressor(n_neighbors=7)
model.fit(x_train,y_train.label.values)

KNeighborsRegressor(n_neighbors=7)

In [71]:
y_pred = model.predict(x_test)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

In [72]:
rmse

1.2709834329476755

In [73]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Assuming y_test and y_pred are the true and predicted values, respectively

# Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error (MSE):", mse)

# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)
print("Root Mean Squared Error (RMSE):", rmse)

# Mean Absolute Error (MAE)
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error (MAE):", mae)

# R-squared (Coefficient of Determination)
r2 = r2_score(y_test, y_pred)
print("R-squared (R2):", r2)


Mean Squared Error (MSE): 1.6153988868274585
Root Mean Squared Error (RMSE): 1.2709834329476755
Mean Absolute Error (MAE): 0.3246753246753247
R-squared (R2): 0.9600577707294115
